import { readFileSync, writeFileSync, mkdirSync, rmSync, cpSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
const manifest = JSON.parse(readFileSync('manifest.json'));
const pkg = JSON.parse(readFileSync('package.json'));
const versions = JSON.parse(readFileSync('versions.json'));
const lock = JSON.parse(readFileSync('package-lock.json'));
if (!/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(manifest.version)) throw Error('Version must use x.y.z without a prefix');
if (lock.version !== manifest.version || lock.packages?.['']?.version !== manifest.version) throw Error('Lockfile version disagrees');
if (pkg.version !== manifest.version || versions[manifest.version] !== manifest.minAppVersion) throw Error('Version files disagree');
if (process.env.RELEASE_TAG && process.env.RELEASE_TAG !== manifest.version) throw Error('Tag must equal manifest version');
const out = resolve('artifacts/release');
rmSync(out, { recursive: true, force: true });
const folder = join(out, manifest.id);
mkdirSync(folder, { recursive: true });
for (const name of ['main.js','manifest.json','styles.css','README.md','INSTALL.md','CHANGELOG.md','RELEASE.md','dev.md','LICENSE']) cpSync(name, join(folder,name));
mkdirSync(join(folder,'docs'), { recursive: true });
for (const name of ['FIRST-RUN.md','AGENT-COMPATIBILITY.md']) cpSync(join('docs',name),join(folder,'docs',name));
cpSync('skills', join(folder,'skills'), { recursive: true });
const zip = `${manifest.id}-${manifest.version}.zip`;
execFileSync('zip', ['-qr', zip, manifest.id], { cwd: out });
for (const name of ['main.js','manifest.json','styles.css']) cpSync(name,join(out,name));
const checksums = [zip,'main.js','manifest.json','styles.css'].map(name => `${createHash('sha256').update(readFileSync(join(out,name))).digest('hex')}  ${name}`).join('\n');
writeFileSync(join(out,'SHA256SUMS.txt'), checksums+'\n');
console.log(join(out,zip));
